language: node_js
node_js:
- 0.12.0
sudo: false
branches:
  except:
  - /-job-\d+/
  only:
  - master
before_install:
- set -e
- npm i -g codeclimate-test-reporter bower karma-cli gulp
install: npm i && bower i
script: npm test
after_script:
- echo "TRAVIS_PULL_REQUEST ${TRAVIS_PULL_REQUEST}"
- echo "TRAVIS_BRANCH ${TRAVIS_BRANCH}"
- codeclimate-test-reporter < coverage/**/lcov.info
after_success:
- gulp build
- if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then FIREBASE_TOKEN="${FIREBASE_TOKEN}" node deploy.prod.js; fi
env:
  global:
  - secure: XSljrhmUvtrMGcQva1Ywn4JX913KBcP6KYZiV9+RqooulXi6TyjBbmXluF0284T02/FWUshpfz6+ufncW1NGWY5ajcvlhpa3QWoCxREqYiOp1UP3IMJ+WBlWGhFKruCUlbfzQ5foYp3tdpBbOq3BPUmgxouMLElOEnUMISPBKgVYaEKdS29MWF7Fgr5lswC8KkbWxMjcoO+1qpnkW5mpnd0V64G0e4OZTKX4JTNhhpPSrXK0/FQ0387Qygb7MMxr4HOus5p29qKmnrVPAT92VzBh4nkaNyJXMWn3ot+MjE08RabNp7HwltVUMac9sNWif7/SmJ6l6x3xbRvwU7yoNjovrdMm/hnFdlWsN2Kkz0nZz/B3Wmu1qBM5frX3GpNh3Af5vhKEn480Aop/ZE050yOfwcRHyqwmoBy9PETiQrV32RoRxjTZ3po6/EsWJIl94dSrYZz8AWvgp8/YPlrOV0HwOY0fr00jrd+NuOQklRFahBH1rQm3UKALFQqF7ydh/dXj91sFkpvPbpkGiNAwfYFXaMOy3NOPBtKtm8YY/IY7gLQ7fuFg/hTBbtVhz/BIuqBpdKrN88p1CcGRAdSPf3QlkCFUeayS1n5a7u24il4f/rHzH8UJjworAVhcN1EyKYlLVLgx6yRk36mcHvmsblhz1AdzHWgAilQ7FYFG9+Y=
  - secure: ZcKZt7sxvNpvC/9wEqXgF04yWUzSgS/7KQTttapHucGA24ESCijNN+6a+tXyXXJb3ApiHl3eqmDZiNaF4GyvhzuWk744mQItJcADwYxrulzPRWjJ6DLA59JwGJvrxsFByAAiWHYssG16R/PLrjyYk8CYZcpakpu6Uz7l88lhHhsFmeawa+NNxRAgB4lxRWNauGUQGaWCWmIpOz7aZOS8idOJp66mqr5hfbDpVCIoSC/+6xNCw3gNdaMaBn2GWRyMLElD0/kTTi2ecHHnQPe9efqdIVQEkJzC6rFiNbDUTWG/UYNJS8GnU9Crq9cDBX5K06LS4FzmAj9wzk+enAFzKX25BcSowkKU276jyeqC+I+L0ft9KAsRlsgg3ivCvTUkQLwWRJwiB3/C50j8WuDgc8vcjVlNejFrE3JlNOZmLhAYMDKudfkbcTZCuxkwKWEg3TTV3s/sd2MA/EmiuV59prK4RTVzO8YGO16sCqT2LonOJ7oNl3NJlaALa7r7TuWjdCmb63A075Eu1I7+oGTouwjJeBooy3GCRHDUHDyp6hxi5o01gFyGvZsSfAaWmLpd5CJC72U0kkyGj5+dqZ59Lxzs38UFuVV1MpxnY1dXSarx6X5gDw0yEPvv2izm4eb9A7l1symXDkD1pWa6hZGmeASZmMrS4lLi990mYEFobAw=
