language: node_js
node_js:
- 0.12.0
sudo: false
branches:
  except:
  - /-job-\d+/
  only:
  - master
before_install:
- set -e
- npm i -g codeclimate-test-reporter bower karma-cli gulp
install: npm i && bower i
script: npm test
after_script:
- echo "TRAVIS_PULL_REQUEST ${TRAVIS_PULL_REQUEST}"
- echo "TRAVIS_BRANCH ${TRAVIS_BRANCH}"
- codeclimate-test-reporter < coverage/**/lcov.info
after_success:
- gulp build
- echo $FIREBASE_TOKEN
- if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then firebase deploy --token "${FIREBASE_TOKEN}";fi
env:
  global:
  - secure: XSljrhmUvtrMGcQva1Ywn4JX913KBcP6KYZiV9+RqooulXi6TyjBbmXluF0284T02/FWUshpfz6+ufncW1NGWY5ajcvlhpa3QWoCxREqYiOp1UP3IMJ+WBlWGhFKruCUlbfzQ5foYp3tdpBbOq3BPUmgxouMLElOEnUMISPBKgVYaEKdS29MWF7Fgr5lswC8KkbWxMjcoO+1qpnkW5mpnd0V64G0e4OZTKX4JTNhhpPSrXK0/FQ0387Qygb7MMxr4HOus5p29qKmnrVPAT92VzBh4nkaNyJXMWn3ot+MjE08RabNp7HwltVUMac9sNWif7/SmJ6l6x3xbRvwU7yoNjovrdMm/hnFdlWsN2Kkz0nZz/B3Wmu1qBM5frX3GpNh3Af5vhKEn480Aop/ZE050yOfwcRHyqwmoBy9PETiQrV32RoRxjTZ3po6/EsWJIl94dSrYZz8AWvgp8/YPlrOV0HwOY0fr00jrd+NuOQklRFahBH1rQm3UKALFQqF7ydh/dXj91sFkpvPbpkGiNAwfYFXaMOy3NOPBtKtm8YY/IY7gLQ7fuFg/hTBbtVhz/BIuqBpdKrN88p1CcGRAdSPf3QlkCFUeayS1n5a7u24il4f/rHzH8UJjworAVhcN1EyKYlLVLgx6yRk36mcHvmsblhz1AdzHWgAilQ7FYFG9+Y=
  - secure: c3divYZQSFgaE7K6MEA0B9OHLvyyi4pKKSoA5mN7s1J5/W0yZUige/KRIRUdKq4ySDCXBT2O3KseGsrNXaJ0uYMF0YLDFuGN7/olCkislbTy37RxU9WeujvZxrXouwYoD3KP33kKY9m/HLgu+ZCzAJA7v4Eu+nVqw29GbBGbsYMe2wfChr++pwJD1lmKakoPCHJdVC20XIHJOScb9coXdMntg0vDw7fx+HI8cmgar4THIjJAnfugfZ8vikRE95n+bdHDj7D08Mp2bDnSS50X0peYXCnYUAHr3vQSKviySrJFMfiOD9hX5xJHBawyEzK8IAQSYJdeK61s1dWQ9frOTSV9QvfZii65ni9eML9bsAXVp+teM1uvRF8pW2vf4z5O6+Dkm1sDY6G2XK3HizKMxaFItFkfaZsSA1fNmsaMhBxpGIoLlPm7cpJbJz1KNeeCUg/VmyZY6GaXEOm9HpTL5MJCj4apWbKf2iOtJyP0nrJanbrM7LgO2ZGjD18P6GUGRTbONKFi026wiTHzq/PiKeNmg8yaS4e68RTB0YaskEW/CuNskyCGsGFZnclRGIa8tQNm/Td/6OTOKFMIIYGGM5HgX+tzUNLuRUvuMVDjhRDNdfkCHKhv0lubHVrZhXtYfejVDOEVrtxSPhNLu6of9NV8f4PE4m3Zn90sb011tp0=
