language: node_js
node_js:
- 0.12.0
sudo: false
branches:
  except:
  - /-job-\d+/
  only:
  - master
before_install:
- set -e
- npm i -g codeclimate-test-reporter bower firebase-tools karma-cli gulp
install: npm i && bower i
script: npm test
after_script:
- echo "TRAVIS_PULL_REQUEST ${TRAVIS_PULL_REQUEST}"
- echo "TRAVIS_BRANCH ${TRAVIS_BRANCH}"
- codeclimate-test-reporter < coverage/**/lcov.info
after_success:
- gulp build
- echo "${FIREBASE_TOKEN}"
- if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then firebase login --token "${FIREBASE_TOKEN}";firebase
  deploy --token "${FIREBASE_TOKEN}"; fi
env:
  global:
  - secure: XSljrhmUvtrMGcQva1Ywn4JX913KBcP6KYZiV9+RqooulXi6TyjBbmXluF0284T02/FWUshpfz6+ufncW1NGWY5ajcvlhpa3QWoCxREqYiOp1UP3IMJ+WBlWGhFKruCUlbfzQ5foYp3tdpBbOq3BPUmgxouMLElOEnUMISPBKgVYaEKdS29MWF7Fgr5lswC8KkbWxMjcoO+1qpnkW5mpnd0V64G0e4OZTKX4JTNhhpPSrXK0/FQ0387Qygb7MMxr4HOus5p29qKmnrVPAT92VzBh4nkaNyJXMWn3ot+MjE08RabNp7HwltVUMac9sNWif7/SmJ6l6x3xbRvwU7yoNjovrdMm/hnFdlWsN2Kkz0nZz/B3Wmu1qBM5frX3GpNh3Af5vhKEn480Aop/ZE050yOfwcRHyqwmoBy9PETiQrV32RoRxjTZ3po6/EsWJIl94dSrYZz8AWvgp8/YPlrOV0HwOY0fr00jrd+NuOQklRFahBH1rQm3UKALFQqF7ydh/dXj91sFkpvPbpkGiNAwfYFXaMOy3NOPBtKtm8YY/IY7gLQ7fuFg/hTBbtVhz/BIuqBpdKrN88p1CcGRAdSPf3QlkCFUeayS1n5a7u24il4f/rHzH8UJjworAVhcN1EyKYlLVLgx6yRk36mcHvmsblhz1AdzHWgAilQ7FYFG9+Y=
  - secure: GSNIk9LfEvJzbZx7H5E1kH0Tp0W4/PXVXmuNKqdqkcPPztf2Ke3H0KHvBIGyylTd9GBQCHbuxkuq1BhZc/4Hyg6pHEEt2c3nJr8xpKE/6TjDGaGCtkeuLzjN67x0Nn7+Y6ZEypXjFLyHd+BAxP+yHFqlxsINQYeJWjlR8Fzf38qh+nl4ygGTgUNKBbnOHxrVqG0B15uA3nyl3y/Mva/pjg8yTP8cNufi72laHGy3/cMMQBzDMLFwjQIu9FuH8jcMXyduBkoHdLUJSIUTETLxE1rHzNyeribVTAN+9XNoNKrWYsTlftEx8C7+60PGhuSf5M3yDAu+72Qc1biLvbFaO7qAkb+GfYYj6lRYDAdL7M+CTxTG3hFbCYosSMU8OuJbmbb9ptgrhlbyMJ0u+tv9piXRuOHTY69BzCZJr0UpiE/9T+eRr6r8LFm0nGr0o56Y0rwU1WTiXqKQbX9mefiaDHx4zHdpMdd503GZc+Ney5u/NRWk3tuKjs9gr8PNS0OkzO35gjrQF+/b6CZPfzMQWsS77Fuw/n9CVCvdft8VmNjfUe18jCRBU0JStXmQm/9il4ntYXkiQkC1S8d2yi7xCyhKLWwlZKhPvj8K8Int1XDeHaXX+e11wr9Ymq0LfbnApvrlI5NeFo/G4iFauyLvo3sWMOZmqsRf+TP3KXFinqw=
  - secure: Mdu0ImX4QBwSHWEXZ8GDdx1u9mqcwzGRs95v3i/KxuLAAo8Cdl5ZaF5sFM0Tmo0T4+jnqIX7wXPbSjHVwCCh0pxMgmpjvk8ZPtA9gFhYehFwT8MEkkm9e83cT3oHWpEh0D0wK8lSkCjP3uItP6ybfLp6ZvQ71NygsRY/J8SnHKyyMr9kBMU9xDFfVZK6TgiIoUhpMuTwQH2B7yrGhnVxp3ZEJMi4USvgVE/MNJwqwuAg7YAY7cBn944ULa5prMVNIyK3zBer0eWkQeOY+S3QbmkVVZpUvltXQmZ8edUQl4Cr8AEqJ4ag7KB9vmQx/fezzSlsnqD0hG8vXUsm2Ll9CTfgD3imJ1VE7+C6tHN9WtnhwFaZmCsBAU0ypq7X4IZ/LunnjoOrbolW3RD5ZctNZnXS7el/XyLqHXm/Cn43ZwpiD7gACcI/IHPFLYctq3jM5/2Bbz97g0u91G4r559zswIZSRkRCFzIk9P9pzs+sgZ41Cd41QuRYzPwT3XLmjTINlEGmnNpTKfUxWWIcVrPvyawJsvXIdzRDGEweswp/anmHGy8Yc+tdNBnt0+G9AlyLGChbT60hXHHtOZCVJIu9NzTH0imFD3vCBBoibG0NgsGZ0+zvAV4cl2JXlyxkWcvQpix3i03l3jD4myZKmXDhVp5IBcHj5BvI0ceOpH6DG4=
  - secure: LuMKnqVTZqYAmMbBUA590aR0P3P6UAj0aiPYDOvFv5a3vTrrnMP9z2HXmmakMWULVteT0zluzpqqMVqxGwANA4WPF6/qZFV3TMU4oyXviE7qqRmZlHaAQ1woFHtUfM6XrlSVkTX/xZHcXeTQ082KNpBBN5tRZllNfdk5mTLLIpJackRIBvgoD2LJzPgR41JOrJePkFpH4EXxdMIG3XbSJyEUUC8K0fQR+Z832JlBHEq8yd4MPrZIsU3zblbe9vgIGWamFPs89CT9J4bO7Tf6sr06+bnFzty/gvFc4RTTMZhe7oImHpdN/1p5+vD8JmkFJxLSHVFTW2OOTLNDkxCofEzvjvIywCyWHs9CtvZTRTyA8YMiebSaDHVSI0xUzjcopVACrO6XYPXl4J9TAQcDir8wSjCFz1yKzKRALnupzUAlHvpigKaZBbBWC/WkUF8V5cm+xAXlCmb9riuOJKlXgyfy1dWUVfwuBgEe2eSPjm6qi72M9S46LpnUyAbQ4YFNpQ1E0AiKAIRLEqh9yyPX0jjAfg7zF4jk6ZMeQq4M6RM39Jn7q0adT0OsSe6hU1+vbmPwA7J4Vi/OMOCGiAoev5PLz6qY9zrXlQSZV7w2e9S+dksBJr5pk4bE91FeDt8Mgj0MlC9asoE2Kr7OFFspxN7vGNMDXF+IcJnI+fJSoQM=
