language: node_js
node_js:
- 0.12.0
sudo: false
branches:
  except:
  - /-job-\d+/
  only:
  - master
before_install:
- set -e
- npm i -g codeclimate-test-reporter bower firebase-tools karma-cli gulp

install: npm i && bower i
script: npm test
after_script:
- echo "TRAVIS_PULL_REQUEST ${TRAVIS_PULL_REQUEST}"
- echo "TRAVIS_BRANCH ${TRAVIS_BRANCH}"
- codeclimate-test-reporter < coverage/**/lcov.info
after_success:
- gulp build
- if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then echo -e "${FIREBASE_USER}\n${FIREBASE_PASSWORD}"
  | firebase --non-interactive login --token "${FIREBASE_TOKEN}";firebase deploy --token "${FIREBASE_TOKEN};
  fi
env:
  global:
  - secure: XSljrhmUvtrMGcQva1Ywn4JX913KBcP6KYZiV9+RqooulXi6TyjBbmXluF0284T02/FWUshpfz6+ufncW1NGWY5ajcvlhpa3QWoCxREqYiOp1UP3IMJ+WBlWGhFKruCUlbfzQ5foYp3tdpBbOq3BPUmgxouMLElOEnUMISPBKgVYaEKdS29MWF7Fgr5lswC8KkbWxMjcoO+1qpnkW5mpnd0V64G0e4OZTKX4JTNhhpPSrXK0/FQ0387Qygb7MMxr4HOus5p29qKmnrVPAT92VzBh4nkaNyJXMWn3ot+MjE08RabNp7HwltVUMac9sNWif7/SmJ6l6x3xbRvwU7yoNjovrdMm/hnFdlWsN2Kkz0nZz/B3Wmu1qBM5frX3GpNh3Af5vhKEn480Aop/ZE050yOfwcRHyqwmoBy9PETiQrV32RoRxjTZ3po6/EsWJIl94dSrYZz8AWvgp8/YPlrOV0HwOY0fr00jrd+NuOQklRFahBH1rQm3UKALFQqF7ydh/dXj91sFkpvPbpkGiNAwfYFXaMOy3NOPBtKtm8YY/IY7gLQ7fuFg/hTBbtVhz/BIuqBpdKrN88p1CcGRAdSPf3QlkCFUeayS1n5a7u24il4f/rHzH8UJjworAVhcN1EyKYlLVLgx6yRk36mcHvmsblhz1AdzHWgAilQ7FYFG9+Y=
  - secure: GSNIk9LfEvJzbZx7H5E1kH0Tp0W4/PXVXmuNKqdqkcPPztf2Ke3H0KHvBIGyylTd9GBQCHbuxkuq1BhZc/4Hyg6pHEEt2c3nJr8xpKE/6TjDGaGCtkeuLzjN67x0Nn7+Y6ZEypXjFLyHd+BAxP+yHFqlxsINQYeJWjlR8Fzf38qh+nl4ygGTgUNKBbnOHxrVqG0B15uA3nyl3y/Mva/pjg8yTP8cNufi72laHGy3/cMMQBzDMLFwjQIu9FuH8jcMXyduBkoHdLUJSIUTETLxE1rHzNyeribVTAN+9XNoNKrWYsTlftEx8C7+60PGhuSf5M3yDAu+72Qc1biLvbFaO7qAkb+GfYYj6lRYDAdL7M+CTxTG3hFbCYosSMU8OuJbmbb9ptgrhlbyMJ0u+tv9piXRuOHTY69BzCZJr0UpiE/9T+eRr6r8LFm0nGr0o56Y0rwU1WTiXqKQbX9mefiaDHx4zHdpMdd503GZc+Ney5u/NRWk3tuKjs9gr8PNS0OkzO35gjrQF+/b6CZPfzMQWsS77Fuw/n9CVCvdft8VmNjfUe18jCRBU0JStXmQm/9il4ntYXkiQkC1S8d2yi7xCyhKLWwlZKhPvj8K8Int1XDeHaXX+e11wr9Ymq0LfbnApvrlI5NeFo/G4iFauyLvo3sWMOZmqsRf+TP3KXFinqw=
  - secure: Mdu0ImX4QBwSHWEXZ8GDdx1u9mqcwzGRs95v3i/KxuLAAo8Cdl5ZaF5sFM0Tmo0T4+jnqIX7wXPbSjHVwCCh0pxMgmpjvk8ZPtA9gFhYehFwT8MEkkm9e83cT3oHWpEh0D0wK8lSkCjP3uItP6ybfLp6ZvQ71NygsRY/J8SnHKyyMr9kBMU9xDFfVZK6TgiIoUhpMuTwQH2B7yrGhnVxp3ZEJMi4USvgVE/MNJwqwuAg7YAY7cBn944ULa5prMVNIyK3zBer0eWkQeOY+S3QbmkVVZpUvltXQmZ8edUQl4Cr8AEqJ4ag7KB9vmQx/fezzSlsnqD0hG8vXUsm2Ll9CTfgD3imJ1VE7+C6tHN9WtnhwFaZmCsBAU0ypq7X4IZ/LunnjoOrbolW3RD5ZctNZnXS7el/XyLqHXm/Cn43ZwpiD7gACcI/IHPFLYctq3jM5/2Bbz97g0u91G4r559zswIZSRkRCFzIk9P9pzs+sgZ41Cd41QuRYzPwT3XLmjTINlEGmnNpTKfUxWWIcVrPvyawJsvXIdzRDGEweswp/anmHGy8Yc+tdNBnt0+G9AlyLGChbT60hXHHtOZCVJIu9NzTH0imFD3vCBBoibG0NgsGZ0+zvAV4cl2JXlyxkWcvQpix3i03l3jD4myZKmXDhVp5IBcHj5BvI0ceOpH6DG4=
  - secure: TlmeApuXU/xZRKTZoB9WrjH156Tu1Vum7+gqV8ekCgobvgIuFeCHBSJ+jb8Fc/YPDKZKPw/jXPdyIII/WsIZ0RqCECR/ZHsAuhIPar7BWrtcHgOfcp2ijF7M7btOCf25zTZ8dKtMty0OFNSjhgRcWQHbC3Io7uWLECzSiGu2T6Qh9YvrFz3G1YdSEHMWG/gNCkuoK//36b10gcssB/UZe0rAoDod2L3tE6CWcO37lIvhn4AH/1pJXo5sR6ZRkmFqGT/zsG9Y2himkms+t1cH1ofNWm2sRZBCsmdVQyqrz2zbp5HIbX0M7XcTmn2zB1KfXzdzkV3bfZphOmJNPUElj97JC5DK12kzJGHBcGQFH5j8bwniONiCxmhnhnvvE18zZfgpkTYS+lzNZ0RofH9mjwMYQcAYdVSdEoY3/Ij5Rs0n/IbBaXCaf5//yEiteZlf6PuFXbUA9j+0v7Qp5b7fMdnuISF3wzg7pwwwQZmqv42MQRsPa004ykJQblmrmrXxDFNpZZ7a0SxGfXgYT2rvDScrLsW+LMH/wH4EKBN9cx2JCaHOp2q8EmXu55QfQf1YWcJTIdmtTGs7Yrzu+seZ37gvjlBWLhc8OkwlJXiR8DMdNNlc3b27OXnVqKMXQ3RM4AeZoQiodsrBhNZG97kzu55kOdqY/B9BcYLMIyE3C6E=
